### ISSUE TITLE
SBI Card - Content Removal Request

### ISSUE THREAD

**Issue by Cybersecurity-Specialist** [swingcake/Data-prep-SBI-Card#3]
Hi,

My name is Caleb, a Security Analyst from iZOOlogic Ltd that works on behalf of our client SBI Card.

Our client noticed this repository and have reported to us that they do not authorize nor have affiliation with you to use their name and post sensitive data pertaining to our client.

We ask that you delete or remove anything related to our client on this repository as this is not authorized and clearly violated the rights of the SBI Card. To avoid any legal action, please remove it immediately or provide proof of affiliation or authorization.

Regards,

Caleb Stark
Security Analyst

**Comment by swingcake** [comment]
This has been resolved with the commit 1f4b2de94375e5e2d9a20f94965b3a84ae29c7b6.

Feel free to comment if you need any clarification regarding the same.
